In [1]:
import pandas  as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
analyze = pd.read_csv('exoplanets.csv')

In [5]:
analyze = analyze.drop(columns=['Unnamed: 0'])

In [10]:
analyze

,planet_name,host_name,orbital_period_[days],orbit_semi-major_axis_[au]),planet_radius,planet_mass,planet_density,eccentricity,equilibrium_temperature_[k],ratio_of_semi-major_axis_to_stellar_radius,...,stellar_radius_[solar_radius],stellar_mass_[solar_mass],stellar_metallicity_[dex],distance_[pc],number_of_planets,insolation_flux_earth,stellar_surface_gravity,stellar_age_[gyr],Datetest,datatest2
0,11 Com b,11 Com,326.03000000,1.290000,12.100,6165.60000,19.100000,0.231000,,,...,19.00,2.70,-0.350,93.1846000,1,,2.31,,1,6
1,11 UMi b,11 UMi,516.21997000,1.530000,12.300,4684.81420,13.800000,0.080000,,,...,29.79,2.78,-0.020,125.3210000,1,,1.93,1.560,1,4
2,14 And b,14 And,185.84000000,0.830000,12.900,1525.50000,3.900000,0.000000,,,...,11.00,2.20,-0.240,75.4392000,1,,2.63,4.500,1,1
3,14 Her b,14 Her,1765.03890112,2.773069,12.600,2586.74645,7.110000,0.372689,,,...,0.93,0.91,0.405,17.9323000,2,,4.45,3.900,1,2
4,16 Cyg B b,16 Cyg B,798.50000000,1.660000,13.500,565.73740,1.260000,0.680000,,,...,1.13,1.08,0.060,21.1397000,1,,4.36,7.400,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,Kepler-228 d,Kepler-228,11.09428600,0.101000,4.040,15.40000,1.280000,0.000000,835,10.900000,...,1.01,0.95,-0.030,1644.6100000,3,122.78,4.47,0.300,4,1
5261,Kepler-229 b,Kepler-229,6.25297200,0.062000,2.200,5.48000,2.830000,0.000000,823,18.940000,...,0.73,0.80,0.160,826.2650000,3,76.22,4.63,1.100,2,5
5262,Kepler-229 c,Kepler-229,16.06863800,0.117000,4.920,21.50000,0.992000,0.000000,600,36.850000,...,0.73,0.80,0.160,826.2650000,3,21.64,4.63,1.100,4,2
5263,Kepler-229 d,Kepler-229,41.19491200,0.220000,3.850,14.20000,1.370000,0.000000,439,70.750000,...,0.73,0.80,0.160,826.2650000,3,6.16,4.63,1.100,3,1
5264,Kepler-23 b,Kepler-23,7.10730000,0.075000,1.900,254.30000,,0.060000,1157,10.643000,...,1.52,1.11,-0.090,835.7560000,3,446.11,4.00,6.000,1,2

In [18]:
analyze['Datetest'] = analyze['planet_radius'].str[:2]
analyze['datatest2'] = analyze['planet_mass'].str[:2]
analyze['datatest3'] = analyze['equilibrium_temperature_[k]'].str[0]
# crea una variable que guarda las filas que tienen '1' en la columna 'Datetest' y '1' en la columna 'datatest2' como condicion
algo = analyze[(analyze['Datetest'] == '1.') & (analyze['datatest2'] == '1.') & (analyze['datatest3'] == '2')]
print(len(algo))
algo

14

,planet_name,host_name,orbital_period_[days],orbit_semi-major_axis_[au]),planet_radius,planet_mass,planet_density,eccentricity,equilibrium_temperature_[k],ratio_of_semi-major_axis_to_stellar_radius,...,stellar_mass_[solar_mass],stellar_metallicity_[dex],distance_[pc],number_of_planets,insolation_flux_earth,stellar_surface_gravity,stellar_age_[gyr],Datetest,datatest2,datatest3
174,GJ 1002 b,GJ 1002,10.34650000,0.045700,1.030,1.08000,5.430000,,231,,...,0.12,-0.250,4.8486700,2,0.67,5.10,,1.,1.,2
1179,Wolf 1069 b,Wolf 1069,15.56400000,0.067200,1.080,1.26000,5.500000,,250,,...,0.17,0.070,9.5834100,1,0.65,4.93,,1.,1.,2
1398,TRAPPIST-1 f,TRAPPIST-1,9.20754000,0.038490,1.045,1.03900,5.022904,0.010070,218,69.543000,...,0.09,0.040,12.4298888,7,0.37,5.24,0.500,1.,1.,2
1425,TOI-700 d,TOI-700,37.42396000,0.163300,1.073,1.25000,5.560000,0.042000,269,82.900000,...,0.42,-0.070,31.1265000,4,0.85,4.81,1.500,1.,1.,2
1438,TOI-561 b,TOI-561,0.44657800,0.010550,1.423,1.59000,3.000000,0.000000,2480,2.646000,...,0.79,-0.330,85.7990000,5,4383.42,4.47,5.000,1.,1.,2
1662,Proxima Cen b,Proxima Cen,11.18680000,0.048560,1.030,1.07000,5.380000,0.020000,234,,...,0.12,,1.3011900,1,0.65,5.16,,1.,1.,2
1949,Kepler-929 b,Kepler-929,0.92103214,0.019200,1.110,1.41000,5.670000,0.000000,2362,2.862300,...,1.01,-0.040,1311.2300000,1,8159.93,4.42,3.470,1.,1.,2
2147,Kepler-78 b,Kepler-78,0.35500744,,1.121,1.96716,5.260000,0.000000,2250,2.660000,...,0.84,-0.140,124.3760000,1,,4.60,0.625,1.,1.,2
2158,Kepler-770 c,Kepler-770,1.47532231,0.030900,1.200,1.87000,5.950000,0.000000,2740,4.913000,...,0.94,-0.010,930.4570000,3,833.59,4.49,4.570,1.,1.,2
3469,Kepler-438 b,Kepler-438,35.23319000,0.166000,1.120,1.46000,5.710000,0.030000,288,73.000000,...,0.54,0.160,195.9428717,1,1.40,4.74,4.400,1.,1.,2
4269,Kepler-1288 b,Kepler-1288,2.76122421,0.043500,1.120,1.46000,5.710000,0.000000,2017,2.560000,...,1.20,0.140,814.0780000,1,3906.36,4.29,2.880,1.,1.,2
4599,Kepler-1531 b,Kepler-1531,1.13854338,0.022000,1.110,1.41000,5.670000,0.000000,2537,4.151000,...,1.16,-0.030,666.3340000,1,9805.45,4.29,2.820,1.,1.,2
4674,Kepler-1589 b,Kepler-1589,0.99166527,0.020500,1.090,1.32000,5.600000,0.000000,2102,3.192000,...,1.18,0.080,1513.1400000,1,5228.78,4.32,2.750,1.,1.,2
4752,Kepler-1649 c,Kepler-1649,19.53527000,0.064900,1.060,1.20000,5.540000,0.000000,234,76.800000,...,0.20,-0.150,92.1913000,2,0.75,5.00,,1.,1.,2